### ISSUE TITLE
No licence indicated

### ISSUE THREAD

**Issue by Moini** [wangshub/python-vad#2]
Hi @wangshub , could you please indicate a licence for your vad script?

I'm playing with it a bit right now (deepspeech ;-)), and I'd like to know if it's safe to share anything that comes out of it.

Thank you!

**Comment by wangshub** [comment]
@Moini , thanks for you advice ~ I am glad konw that this code will be helpful for you.

**Comment by Moini** [comment]
Thank you very much, @wangshub !!! :-D
